/* Generated by build.py - DO NOT EDIT BY HAND.
   Edit markdown/*.md instead, then run:  python build.py  */
const PROJECT_TEXT = {
  "tactile-racing-game": [
    {
      "heading": "",
      "paragraphs": [
        "<p>Under my leadership, my GEEN 1400 projects team created a unique two-player racing game which features two tactile stick-shift models as controllers and RPM gauges instead of a screen.</p>",
        "<p>My team and I noticed the lack of affordable, user-friendly video-game-like experiences on the market, inspiring us to create a first-of-its-kind console that includes all the fun and none of the unnecessary complexity or expenses of a traditional video game console.</p>",
        "<p>The controllers are remixed from an existing 3d printable fidget-toy car shifter model, which I evolved into a functional and durable controller for our game. Our controller is modified to fit six limit switches, located carefully to be adequately sensitive to shifting motions but not overly fragile.</p>"
      ]
    },
    {
      "heading": "Logic and code",
      "paragraphs": [
        "<p>Before writing code, we made a diagram of all possible inputs to outputs.</p>",
        "<p>I cleanly translated our I/O diagram into Arduino logic with an object-oriented coding approach. The Controller class defines variables which each Controller object needs to keep track of: current gear, its own full pinout, and the state of its corresponding LED. The broader Car class defines functions and variables for each player, as well as holding a reference to the corresponding Controller. The finished code was robust enough to keep track of all the necessary variables for each controller, NeoPixel strip, and servo, and carefully time the logical handling of all the inputs and outputs to create a fluid, enjoyable game experience.</p>"
      ]
    },
    {
      "heading": "Wiring",
      "paragraphs": [
        "<p>I laid out the wiring in such a way to minimize unnecessary jumper cables and maximize organization in the case of malfunction, completely redoing the wiring several times to make it as failsafe and clean as possible.</p>"
      ]
    }
  ],
  "guitar-restoration": [
    {
      "heading": "",
      "paragraphs": [
        "<p>During my senior year of high school, some family friends gave me a very broken electric guitar. The headstock was cracked clean in half. The pickguard was shattered and filthy. And it didn’t make any noise at all.</p>",
        "<p>Upon further research, it was briefly made sometime in the 1960s by a now-defunct company, and had no documentation whatsoever. It really seemed like a lost cause. I took off the pickguard and cleaned everything up; after spending increasingly long hours admiring its components, I figured I might as well just fix the thing.</p>"
      ]
    },
    {
      "heading": "Wiring",
      "paragraphs": [
        "<p>I spent lots of hours fiddling with different configurations of the tone circuitry. With an MP3 player hooked up to where the pickups should be, I was able to play with various filter and volume knob configurations. I decided on buying an “orange drop” low-pass filter. The original potentiometers turned out to be functional after some internal cleaning.</p>"
      ]
    },
    {
      "heading": "Pickguard",
      "paragraphs": [
        "<p>(The pickguard is the name for the plastic plate that protects the wood face of the guitar. In my case, all the electronics were mounted to it, instead of to the wood itself). I thought I was done with the guitar after I’d redone the wiring; I put a bit of superglue on the original pickguard and called it good. It took exactly one jam session with friends to re-break it--I pulled out the instrument cable at a funny angle, and the pickguard cracked agin.</p>",
        "<p>I took off the broken pickguard, put it together one last time, and stuck it in my school’s industrial photocopier. After using Fusion 360 to trace and scale it, I laser cut a new one out of clear acrylic and used a dremel to scuff some pretty patterns into it. Having a clear pickguard is unusual, and leads to some interesting possibilities…</p>"
      ]
    },
    {
      "heading": "Lighting",
      "paragraphs": [
        "<p>I installed a strip of neopixels into the electronics cavity of the wood, and wired them to the D+, power, and ground of a USB-C port which I mounted in the pickguard. I chose to keep all circuitry out of the guitar; anytime I want to change the lighting control, I don’t need to take the guitar apart. The guitar simply houses the lights themselves and no more.</p>",
        "<p>As for the external lighting controller: an Adafruit Feather M0 sends a lighting signal to a logic level shifter, which passes it on through the USB C cable. Instead of buying new parts, I reused a broken LG phone I had: the LG’s battery is perfect for powering the Neopixels for hours on end, and I repurposed the LG itself to charge its own old battery so I wouldn’t need to create a separate charging circuit.</p>",
        "<p>Finally, I use the FastLED library to program whatever lighting effects I desire, and connect my phone to the Feather over Bluetooth to command it to switch between stored effects.</p>"
      ]
    }
  ],
  "sdr-mount": [
    {
      "heading": "Compact phone and SDR transceiver module",
      "paragraphs": [
        "<p>A quick project for the RF lab-- I was tasked to design a portable, compact way to hold together an Android phone, SDR hardware, and a biconical ultra wideband antenna. My solution was this 3d-printed mount I designed in Onshape. The clamp, held shut with two rubber bands, holds the phone in place; the SDR transceiver mounts to the back with velcro strips. It took a few iterations to get the clamps to slide smoothly and keep the rubber bands out of the way.</p>"
      ]
    }
  ],
  "rf-research": [
    {
      "heading": "Placeholder Heading",
      "paragraphs": [
        "<p>Content coming soon.</p>"
      ]
    }
  ],
  "video-game": [
    {
      "heading": "Placeholder Heading",
      "paragraphs": [
        "<p>A Roblox game I worked on for a couple years in high school. More info to come.</p>"
      ]
    }
  ],
  "placeholder": [
    {
      "heading": "Placeholder Heading",
      "paragraphs": [
        "<p>Content coming soon.</p>"
      ]
    }
  ]
};
